// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/code-devel-cover/CodeCover/config"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

// Injectors from wire.go:

func InitializeApplication(config2 *config.Config, db *gorm.DB) (application, error) {
	loginMiddleware := provideLogin(config2)
	scmClientService := provideSCMClientService(config2)
	databaseService := provideDatabaseService(db)
	userStore := provideUserStore(databaseService)
	userService := provideUserService(userStore, scmClientService)
	session := provideSession()
	routers := provideRouter(loginMiddleware, scmClientService, userService, session, config2)
	mainApplication := newApplication(routers, databaseService)
	return mainApplication, nil
}
